/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as GameIndexImport } from './routes/game/index'
import { Route as GameSendImport } from './routes/game/send'
import { Route as GameFishingImport } from './routes/game/fishing'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GameIndexRoute = GameIndexImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRoute,
} as any)

const GameSendRoute = GameSendImport.update({
  id: '/game/send',
  path: '/game/send',
  getParentRoute: () => rootRoute,
} as any)

const GameFishingRoute = GameFishingImport.update({
  id: '/game/fishing',
  path: '/game/fishing',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/game/fishing': {
      id: '/game/fishing'
      path: '/game/fishing'
      fullPath: '/game/fishing'
      preLoaderRoute: typeof GameFishingImport
      parentRoute: typeof rootRoute
    }
    '/game/send': {
      id: '/game/send'
      path: '/game/send'
      fullPath: '/game/send'
      preLoaderRoute: typeof GameSendImport
      parentRoute: typeof rootRoute
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/game/fishing': typeof GameFishingRoute
  '/game/send': typeof GameSendRoute
  '/game': typeof GameIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/game/fishing': typeof GameFishingRoute
  '/game/send': typeof GameSendRoute
  '/game': typeof GameIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/game/fishing': typeof GameFishingRoute
  '/game/send': typeof GameSendRoute
  '/game/': typeof GameIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/game/fishing'
    | '/game/send'
    | '/game'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/login' | '/game/fishing' | '/game/send' | '/game'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/game/fishing'
    | '/game/send'
    | '/game/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  GameFishingRoute: typeof GameFishingRoute
  GameSendRoute: typeof GameSendRoute
  GameIndexRoute: typeof GameIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  GameFishingRoute: GameFishingRoute,
  GameSendRoute: GameSendRoute,
  GameIndexRoute: GameIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/login",
        "/game/fishing",
        "/game/send",
        "/game/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/game/fishing": {
      "filePath": "game/fishing.tsx"
    },
    "/game/send": {
      "filePath": "game/send.tsx"
    },
    "/game/": {
      "filePath": "game/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
